with source as (
    select * from {{ source('bronze', 'bronze_wellbore_all') }}
),

renamed as (
    select
        wlbWellboreName                 as wellbore_name,
        wlbNpdidWellbore                as npdid_wellbore,
        wlbWell                         as well_name,
        wlbDrillingOperator             as drilling_operator,
        wlbProductionLicence            as wellbore_production_licence,
        wlbPurpose                      as wellbore_purpose,
        wlbStatus                       as wellbore_status,
        wlbContent                      as wellbore_content,
        wlbWellType                     as wellbore_type,
        wlbEntryDate                    as wellbore_spud_date,
        wlbCompletionDate               as wellbore_completed_date,
        wlbField                        as field_name,
        wlbDrillPermit                  as wellbore_drilling_permit,
        wlbBottomHoleTemperature        as wellbore_bottom_hole_temperature_degc,
        wlbMaxInclation                 as wellbore_maximum_inclination_deg,
        wlbKellyBushElevation           as wellbore_kelly_bushing_elevation_meters,
        wlbKickOffPoint                 as wellbore_kick_off_point_meters,
        wlbFinalVerticalDepth           as wellbore_tvd_meters,
        wlbTotalDepth                   as wellbore_md_meters,
        wlbWaterDepth                   as wellbore_water_depth_meters,
        wlbAgeAtTd                      as wellbore_oldest_penetrated_age,
        wlbFormationAtTd                as wellbore_oldest_penetrated_formation,
        wlbMainArea                     as wellbore_main_area,
        wlbDrillingFacility             as wellbore_drilling_facility,
        wlbDrillingFacilityFixedOrMove  as wellbore_drilling_facility_category,
        wlbFacilityTypeDrilling         as wellbore_drilling_facility_type,
        wlbProductionFacility           as wellbore_production_facility,
        wlbMultilateral                 as wellbore_multilateral_flag,
        wlbPurposePlanned               as wellbore_planned_purpose,
        wlbContentPlanned               as wellbore_planned_content,
        wlbEntryYear                    as wellbore_entry_year,
        wlbCompletionYear               as wellbore_completion_year,
        wlbReclassFromWellbore          as wellbore_reclassified_from,
        wlbDateReclass                  as wellbore_reclassified_date,
        wlbFormationWithHc1             as wellbore_1st_level_with_hc_formation,
        wlbAgeWithHc1                   as wellbore_1st_level_with_hc_age,
        wlbFormationWithHc2             as wellbore_2nd_level_with_hc_formation,
        wlbAgeWithHc2                   as wellbore_2nd_level_with_hc_age,
        wlbFormationWithHc3             as wellbore_3rd_level_with_hc_formation,
        wlbAgeWithHc3                   as wellbore_3rd_level_with_hc_age,
        wlbDrillingDays                 as wellbore_drilling_days,
        wlbNsUtm                        as wellbore_ns_utm_meters,
        wlbEwUtm                        as wellbore_ew_utm_meters,
        wlbUtmZone                      as wellbore_utm_zone,
        prlNpdidProdLicenceTarget       as npdid_production_licences_target,
        dscNpdidDiscovery               as npdid_discovery,
        fldNpdidField                   as npdid_field,
        fclNpdidFacilityDrilling        as npdid_drilling_facility,
        fclNpdidFacilityProducing       as npdid_production_facility,
        wlbNpdidWellboreReclass         as npdid_wellbore_reclassified_from,
        prlNpdidProductionLicence       as npdid_production_licence_drilled_in,
        wlbAliasName                    as wellbore_alias_name,
        wlbSubSea                       as wellbore_subsea_flag,
        wlbPluggedDate                  as wellbore_plugged_date,
        wlbPluggedAbandonDate           as wellbore_plug_and_abandon_date,
        wlbNpdidSiteSurvey              as npdid_site_survey,
        wlbDateUpdated                  as wellbore_updated_date
    from source
)

select * from renamed